### ISSUE TITLE
Ice King's Curse doesn't work

### ISSUE THREAD

**Issue by Partonetrain** [cleannrooster/spellblades-1.20.1#10]
The spell doesn't damage enemies or unfreeze the player.
![2024-03-24_19 00 45](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/2b3f4ef8-8307-48dc-877c-d2071b0a858c)

It also has a format error in its tooltip:
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/ae378bf5-ff55-4ae2-b14e-e2095e711bab)

**Comment by cleannrooster** [comment]
It's not supposed to damage, I'll look into it not unfreezing.

**Comment by Partonetrain** [comment]
I thought vanilla freeze applied damage over time? That's not what was happening to mobs for me in my testing world.
Also, as the screenshot shows, I was in creative, but I don't think that makes a difference

**Comment by Partonetrain** [comment]
It does unfreeze the player (I was mistaken), but I'm not sure what inflicting freeze on enemies is supposed to do if it wears off so quickly, but I guess the main point is the Strength effect
