### ISSUE TITLE
Request: More items related to the Souls Element, for Necromancer!

### ISSUE THREAD

**Issue by FumpleWumper** [cleannrooster/spellblades-1.20.1#11]
Necromancer was added recently but it hasn't received any love from any addons yet, having no spellbooks or any sort of gear to amplify its Soul damage. It would be great to have an option to spec into Souls with the spellblades, since there's gear for the other three elements. Thank you for reading, and please consider giving Necromancer some weapons and spells to work with, it'd be amazing!

**Comment by cleannrooster** [comment]
Hi, I have recently released the Druids mod, focusing on Soul and Lightning. Check it out here: https://legacy.curseforge.com/minecraft/mc-mods/druids-of-storm-and-spirit
