### ISSUE TITLE
Crash player on server 1.20.1

### ISSUE THREAD

**Issue by Y0JJO** [cleannrooster/spellblades-1.20.1#19]
[crash.txt](https://github.com/user-attachments/files/17121773/crash.txt)
Hello!
The problem is as follows: When a player takes in his hands or inventory item SoulRender, it instantly crashes\kikaket from the server. Tried to install Neruina, but it does not fix the problem.

**Comment by cleannrooster** [comment]
This should be fixed in the next version

**Comment by Y0JJO** [comment]
Thanks!
