### ISSUE TITLE
Problems with translation 1.20.1

### ISSUE THREAD

**Issue by Zt192** [cleannrooster/spellblades-1.20.1#21]
The modification does not have most of the translation keys, it is simply impossible to translate the descriptions of many items... This makes it very difficult for translators, maybe version 1.20.1 is not so relevant anymore, but it is still popular. So please add them sometime, so that the mod can be translated completely.

**Comment by cleannrooster** [comment]
Hi, sorry about the issues! I will get to this at some point, admittedly it is rather low priority.

**Comment by Zt192** [comment]
Thank you for your reply
