### ISSUE TITLE
Hexblade invasion not happening and no loot from friendly hexblade portal/Magus.

### ISSUE THREAD

**Issue by Leitoooor** [cleannrooster/spellblades-1.20.1#22]
I made a big modpack (almost 300 mods) for my SMP with the newest version of the mod.
After some days of playing I noticed I was not getting any hex invasion, even after using a lot of magic.
I tried spawning some friendly invasions (with the hexblade offering) and they did not drop the prismatic pearl.
I observed this problem in both 2.0.0 and 2.0.1.
Logs doesn't seen to give me any usefull information and I have no idea if this is a compatibility issue with another mod.

**Comment by Leitoooor** [comment]
Tried killing the Magus in creative, both in Overworld and Glass Ocean, no loot dropped from either.
Going back to 1.21.3 seems to fix the problem.

**Comment by cleannrooster** [comment]
There was indeed a problem with loot.
This is fixed in the recently uploaded update.
I did confirm however that invasions are happening.
Perhaps you're just unlucky, or you're carrying a Hexblade?

**Comment by Leitoooor** [comment]
Just saw that you posted a newer version, I was in 2.0.1 when those happened.
I'll update my game, ty.

Also I was not carrying a hexblade or anything, it could be me being unlucky but I was playing for hours, using magic and everything and did not get a single invasion. Also made sure the gamerule was set to true.
Will see if it changes for some reason when I update to 0.2.2.

**Comment by Leitoooor** [comment]
Just updated and did some testing, everything seems to be working fine.
Haven't seen a natural invasion yet but considering I was playing in 1.21.3 too, not only 2.0.1, which I've seen work before it's probably some real bad luck on my side.
Anyways, love the mod, it's always on my packs, ty for the hard work.
