### ISSUE TITLE
1.20.1 Server crash. Ticking Entity

### ISSUE THREAD

**Issue by FuturisticDruid** [cleannrooster/spellblades-1.20.1#3]
Server crashed after one of the players killed a hexblade trader and went near one of the portals that spawned
crashlog says something about simply skills and spell engine also
[crash-2023-10-15_02.00.49-server.txt](https://github.com/cleannrooster/spellblades-1.20.1/files/12908398/crash-2023-10-15_02.00.49-server.txt)

**Comment by FuturisticDruid** [comment]
just noticed it said something about simply skills also

**Comment by FuturisticDruid** [comment]
can't restart server. it crashes again with the same thing

**Comment by cleannrooster** [comment]
Sorry for the delay, was busy this weekend. 
For now, install Neurina on the server to fix the problem, as I look into the root of the issue.

**Comment by cleannrooster** [comment]
Should be fixed on the end of Sweeney by a couple days ago.
