### ISSUE TITLE
Is there a way to modify damage of spells?

### ISSUE THREAD

**Issue by Ricenami** [cleannrooster/spellblades-1.20.1#4]
Hi love your mod. I had a question regarding the spell Whirlwind. It's default on the claymores and it does so much damage it can kill an iron golem with 100 hp in 3 seconds, I want to modify the damage of whirlwind, not the damage of the claymore.

I tried using a datapack to modify the damage, but the whirlwind.json file doesn't include damage numbers.

I would appreciate any feedback.

Cheers!

**Comment by cleannrooster** [comment]
Hi!
You can modify the "spell power coefficient" under "impact" and "action", by default it's 1.5.
As an example, lowering it to 1 would reduce the damage by 1/3.

**Comment by Ricenami** [comment]
Changing the impact to 0 doesn't negate the damage from whirlwind, is this working properly?

**Comment by cleannrooster** [comment]
I believe due to the way Spell Engine is made, it will always do some damage. There is also a minimum damage that Whirlwind does, regardless of coefficient.

**Comment by cleannrooster** [comment]
This is 1.20.1, correct? In 1.19.2, whirlwind damage is not configurable.

**Comment by Ricenami** [comment]
I'm sorry for any misunderstanding, this is in 1.19.2. In that case, is editing whirlwind not possible? Even with datapacks?

**Comment by cleannrooster** [comment]
Hi, checking up. Just to clarify, editing whirlwind is not possible even with datapacks in 1.19.2. I will only update 1.19.2 if significant need arises, since rewriting it to support datapacks would involve significant time.
