### ISSUE TITLE
Pig crash the game

### ISSUE THREAD

**Issue by wdog5** [cleannrooster/spellblades-1.20.1#7]
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/40519136/2d656625-573d-4249-bcc3-9df3676f76dd)
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/40519136/04796ab0-993c-456d-ae92-1f5687b077e2)
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/40519136/885f4bd7-a395-41d8-988e-93abbf1d428a)
You'd better add a NPE check(Null Point Exception check to avoid such issues)
Pig doesn't have any attack damage attributes

**Comment by wdog5** [comment]
`if (damageinstance != null) {
}`
just add this could fix this bug

**Comment by Partonetrain** [comment]
This is definitely a bug, but like, how did you encounter this? Equip a pig with Herald armor?

**Comment by cleannrooster** [comment]
Hi, I believe this is fixed in the most recent update, tell me if you still
encounter issues.
