### ISSUE TITLE
Frigid Herald chestplate has extra geometry on back left

### ISSUE THREAD

**Issue by Partonetrain** [cleannrooster/spellblades-1.20.1#8]
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/5e284a1c-0830-42c3-8fc4-d43944364cd7)
It looks like it's the front of the chest piece. Considering it's not on the other side, it doesn't seem intentional

**Comment by cleannrooster** [comment]
Hi, this is intentional, it's supposed to look like the end of a scarf
hanging off. Maybe it could use some revision.
