### ISSUE TITLE
Armors appear to be incompatible with mods that can change the tooltips (like ToolStats and Armor Set Bonuses)

### ISSUE THREAD

**Issue by Partonetrain** [cleannrooster/spellblades-1.20.1#9]
Vanilla armor:
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/ce2d410b-ba1c-4853-a1cf-be2ab8c35ebc)
Spellblades armor:
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/8a2b50a9-6131-4216-9d54-81a2dd0148be)

(I also have Legendary Tooltips but that's not a problem as seen here:)
![image](https://github.com/cleannrooster/spellblades-1.20.1/assets/19861808/dc608088-1636-47cc-ba5c-4d24ae362b43)

Very strange issue, I've been looking at the code but all Spellblades armor extends ArmorItem as expected. Will continue to investigate.

**Comment by cleannrooster** [comment]
Hi, sorry I just got to this. I will investigate this myself.

**Comment by Partonetrain** [comment]
Does not appear to be an issue anymore

**Comment by cleannrooster** [comment]
Yeah I fixed it, forgot to put it in the update notes lol
